config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :image_processing_requests
  mount Sidekiq::Web, at: '/sidekiq'

  resources :image_processing_requests
  root to: 'image_processing_requests#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :image, storage: :s3,
                            s3_credentials: File.open(File.join(Rails.root, 'config', 's3.yml')),
                            url: ':s3_domain_url',
                            path: '/images/:id_:basename.:extension'
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/image_processing_request.rb
class ImageProcessingRequest < ActiveRecord::Base
  belongs_to :original_image, class_name: 'Image'
  belongs_to :processed_image, class_name: 'Image'

  accepts_nested_attributes_for :original_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: :json_request?

  protected
  def json_request?
    request.format.json?
  end
end

app/controllers/image_processing_requests_controller.rb
class ImageProcessingRequestsController < ApplicationController
  before_action :set_image_processing_request, only: [:show, :edit, :update, :destroy]

  # GET /image_processing_requests
  # GET /image_processing_requests.json
  def index
    @image_processing_requests = ImageProcessingRequest.all
  end

  # GET /image_processing_requests/1
  # GET /image_processing_requests/1.json
  def show
  end

  # GET /image_processing_requests/new
  def new
    @image_processing_request = ImageProcessingRequest.new
  end

  # GET /image_processing_requests/1/edit
  def edit
  end

  # POST /image_processing_requests
  # POST /image_processing_requests.json
  def create
    @image_processing_request = ImageProcessingRequest.new(image_processing_request_params)

    respond_to do |format|
      if @image_processing_request.save
        ImageProcessingRequestWorker.perform_async(@image_processing_request.id)

        format.html { redirect_to @image_processing_request, notice: 'Image processing request was successfully created.' }
        format.json { render :show, status: :created, location: @image_processing_request }
      else
        format.html { render :new }
        format.json { render json: @image_processing_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_processing_requests/1
  # PATCH/PUT /image_processing_requests/1.json
  def update
    respond_to do |format|
      if @image_processing_request.update(image_processing_request_params)
        format.html { redirect_to @image_processing_request, notice: 'Image processing request was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_processing_request }
      else
        format.html { render :edit }
        format.json { render json: @image_processing_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_processing_requests/1
  # DELETE /image_processing_requests/1.json
  def destroy
    @image_processing_request.destroy
    respond_to do |format|
      format.html { redirect_to image_processing_requests_url, notice: 'Image processing request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_processing_request
      @image_processing_request = ImageProcessingRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_processing_request_params
      params.require(:image_processing_request).permit({original_image_attributes: [:image]}, :command_string, :callback_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_processing_requests_helper.rb
module ImageProcessingRequestsHelper
end

app/views/image_processing_requests/_form.html.erb
<%= form_for @image_processing_request, :html => { :class => "form-horizontal image_processing_request", :multipart => true } do |f| %>

  <% if @image_processing_request.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@image_processing_request.errors.count, "error") %> prohibited this image_processing_request from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @image_processing_request.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :original_image, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <img id='original_image_preview' style='width: 100%; height: auto;'>
      <%= f.file_field :original_image, :class => 'form-control',
                                        :name => 'image_processing_request[original_image_attributes][image]',
                                        :accept => 'image/*' %>
    </div>
    <%=f.error_span(:original_image) %>
  </div>
  <div class="form-group">
    <%= f.label :command_string, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :command_string, :class => 'form-control' %>
    </div>
    <%=f.error_span(:command_string) %>
  </div>
  <div class="form-group">
    <%= f.label :callback_url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :callback_url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:callback_url) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                image_processing_requests_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

<script>
  $(document).ready(function() {
    var $originalImageField = $('#image_processing_request_original_image');
    var $originalImage = $('#original_image_preview');

    // Set image preview when you use the file field
    $originalImageField.change(function(event) {
      var file = this.files[0];
      var reader = new FileReader();

      reader.onloadend = function() {
        $originalImage.attr('src', reader.result);
      }

      reader.readAsDataURL(file);
    })
  });
</script>

app/views/image_processing_requests/edit.html.erb
<%- model_class = ImageProcessingRequest -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/image_processing_requests/index.html.erb
<%- model_class = ImageProcessingRequest -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:original_image_id) %></th>
      <th><%= model_class.human_attribute_name(:processed_image_id) %></th>
      <th><%= model_class.human_attribute_name(:processed) %></th>
      <th><%= model_class.human_attribute_name(:command_string) %></th>
      <th><%= model_class.human_attribute_name(:callback_url) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @image_processing_requests.each do |image_processing_request| %>
      <tr>
        <td><%= link_to image_processing_request.id, image_processing_request_path(image_processing_request) %></td>
        <td align='center'>
          <img class='original_image_preview'
               src='<%= image_processing_request.original_image.try(:image).try(:url) %>'
               style='max-width: 80px; max-height: 80px; display: block;'>
          <%= image_processing_request.original_image_id %>
        </td>
        <td align='center'>
          <img class='processed_image_preview'
               src='<%= image_processing_request.processed_image.try(:image).try(:url) %>'
               style='max-width: 80px; max-height: 80px; display: block;'>
          <%= image_processing_request.processed_image_id %>
        </td>
        <td><%= image_processing_request.processed %></td>
        <td><%= image_processing_request.command_string %></td>
        <td><%= image_processing_request.callback_url %></td>
        <td><%=l image_processing_request.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_image_processing_request_path(image_processing_request), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      image_processing_request_path(image_processing_request),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_image_processing_request_path,
            :class => 'btn btn-primary' %>

app/views/image_processing_requests/new.html.erb
<%- model_class = ImageProcessingRequest -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/image_processing_requests/show.html.erb
<%- model_class = ImageProcessingRequest -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<table class='table table-striped'>
  <tbody>
    <tr>
      <td><strong><%= model_class.human_attribute_name(:id) %>:</strong></td>
      <td><%= @image_processing_request.id %></td>
    </tr>
    <tr>
      <td><strong><%= model_class.human_attribute_name(:original_image_id) %>:</strong></td>
      <td>
        <%= @image_processing_request.original_image_id %>
        <img id='original_image_preview' src='<%= @image_processing_request.original_image.try(:image).try(:url) %>' style='max-witdh: 320px; max-height: 320px; display: block;'>
      </td>
    </tr>

    <tr>
      <td><strong><%= model_class.human_attribute_name(:processed_image_id) %>:</strong></td>
      <td>
        <%= @image_processing_request.processed_image_id %>
        <img id='processed_image_preview' src='<%= @image_processing_request.processed_image.try(:image).try(:url) %>' style='max-witdh: 320px; max-height: 320px; display: block;'>
      </td>
    </tr>

    <tr>
      <td><strong><%= model_class.human_attribute_name(:processed) %>:</strong></td>
      <td><%= @image_processing_request.processed %></td>
    </tr>

    <tr>
      <td><strong><%= model_class.human_attribute_name(:command_string) %>:</strong></td>
      <td><%= @image_processing_request.command_string %></td>
    </tr>

    <tr>
      <td><strong><%= model_class.human_attribute_name(:callback_url) %>:</strong></td>
      <td><%= @image_processing_request.callback_url %></td>
    </tr>
  </tbody>
</table>

<%= link_to t('.back', :default => t("helpers.links.back")),
              image_processing_requests_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_image_processing_request_path(@image_processing_request), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              image_processing_request_path(@image_processing_request),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageProcessingServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container-fluid'>
  <%= yield %>
</div>

</body>
</html>